### ISSUE TITLE
Resolve properties from parent POMs [Maven]

### ISSUE THREAD

**Issue by jirutka** [versioneye/versioneye_issues#10]
When dependency’s version is defined with property from parent POM, VersionEye (web) doesn’t resolve it:

```
Current   | Locked             | Dependency
----------+--------------------+---------------
1.7.7     | ${slf4j.version}   | jcl-over-slf4j
```

https://www.versioneye.com/user/projects/536765e5051e5c78450000d1

**Comment by reiz** [comment]
How did you create the project? 
Did you use the https://github.com/versioneye/versioneye_maven_plugin to create or update the project?

**Comment by reiz** [comment]
@jirutka VersionEye resolves the variables if you are using the VersionEye Maven Plugin: 
https://github.com/versioneye/versioneye_maven_plugin 

Through the GitHub API we don't resolve it, because a pom.xml can have children and parents and resolving that kind of transitive dependency via the GitHub API is kind of overkill ;-)

**Comment by jirutka** [comment]
Nope, I’ve created it from GitHub. Thanks for your answer, I’ll try the Maven plugin.
