### ISSUE TITLE
License management

### ISSUE THREAD

**Issue by jcarsique** [versioneye/versioneye_issues#12]
Hi,

How are evaluated the licenses? 

How to fix a missing/unknown license?
For instance, [com.codahale.metrics:metrics-graphite:3.0.0](https://www.versioneye.com/java/com.codahale.metrics:metrics-graphite/3.0.0) has "License: UNKNOWN" but its parent [com.codahale.metrics:metrics-parent:3.0.0](https://www.versioneye.com/java/com.codahale.metrics:metrics-parent/3.0.0) states "Apache License 2.0".
There are more tricky examples where the POM is not properly fit and the license is only stated on the author site. A contributing feature allowing users to complete information could be useful but would optionally require moderation and justification resource links.

How to merge licenses? 
Is the http://mojo.codehaus.org/license-maven-plugin/ used? If so, that plugin has a licenseMerges option and versioneye users could send pull-requests on a common merge resource file.
For instance, "CDDL-1.0" and "Common Development and Distribution License 1.0" are the same.
Another example: "Apache License 2.0" ([org.apache.xmlbeans:xmlbeans:2.3.0](https://www.versioneye.com/java/org.apache.xmlbeans:xmlbeans/2.3.0)) and "Apache License V2.0" ([net.sourceforge.yarfraw:yarfraw:0.92](https://www.versioneye.com/java/net.sourceforge.yarfraw:yarfraw/0.92)) are the same license.

**Comment by reiz** [comment]
@jcarsique Good questions :-) 

I guess currently we don't fetch the License from the parent pom. I will double check that and improve it. 

A contributing feature for core committers is already on the Roadmap, that's coming soon. A couple core committers confirmed already that they would like to join. 

VersionEye is already doing normalization on the License names. That is something that has to be improved permanently. I just added your examples to the code. That will go online today. Currently we don't use the license-maven-plugin, but I will check it out.

**Comment by reiz** [comment]
@jcarsique Beside that we are working on a License crawler which crawls Licenses from git repositories. I guess that will add a lot of additional information to our database.

**Comment by jcarsique** [comment]
Tell me if I can contribute to the code or the license database.
I guess this can be an important Versioneye feature, in complement or replacement of existing custom tools and Maven repository features.
Thank you.

**Comment by reiz** [comment]
@jcarsique I want to open source the license module of VersionEye, to get reviews and contributions from the community. But our business guy stopped me :-) We need first a CLA (Contributor License Agreement) for everyone who want's to contribute. Because VersionEye need to own the IP to be able to ship the code with the VersionEye Enterprise VM to B2B clients. 
But it's in the queue and it's coming ;-)

**Comment by reiz** [comment]
Hi @jcarsique. I just open sourced VersionEye, see here the blog post: https://blog.versioneye.com/2016/06/28/versioneye-goes-open-source/. 

Here is the code for the license normalizer: https://github.com/versioneye/versioneye-core/blob/master/lib/versioneye/models/traits/license_normalizer.rb. 
And here are the tests: https://github.com/versioneye/versioneye-core/blob/master/spec/versioneye/models/license_spec.rb 

If you have more questions or suggestions to the license normalisation, please open a ticket directly at the versioneye-core project or even better send a pull request ;-)

**Comment by manoelcampos** [comment]
Hello @reiz,

Sorry if this is not the best channel for questions, but I've googled, checked the documentation and FAQ and I haven't found a solution.

I have [a maven project](https://github.com/manoelcampos/cloudsim-plus) which has multiple modules. I'm using maven 3.39 with maven versioneye-maven-plugin 3.11.0. For every pom.xml I included the top level tag below:
```xml
<licenses>
  <license>
      <name>GPLv3</name>
      <url>http://www.gnu.org/licenses/lgpl-3.0.txt</url>
  </license>
</licenses>
```
The license name is one the strings that are recognised by the [License Normalizer](https://github.com/versioneye/versioneye-core/blob/master/lib/versioneye/models/traits/license_normalizer.rb). I use `mvn versioneye:update` but when I access my [VersionEye project page](https://www.versioneye.com/user/projects/5841f4dfb1c38c0aa1cd46f1) my maven modules licenses are yet shown as **UNKNOWN**.

Thanks in advance.

**Comment by reiz** [comment]
Hi @manoelcampos. The link to your VersionEye project doesn't work anymore. Did you remove the project?

**Comment by reiz** [comment]
Hi @manoelcampos. I just found your project and took a look to your parent pom.xml file. The first thing which looks odd to me is that you are hard coding the project ID into the pom.xml. I send you a pull request [here](https://github.com/manoelcampos/cloudsim-plus/pull/52) which is removing that. The Maven Plugin does create for each pom.xml file 1 VersionEye project. 1 for the parent pom and 1 for each child module. After that the child projects are merged into the parent project. So you have alle files in one project view at VersionEye. But for that it is necessary NOT to hard code the project ID. 

Other from that I saw that the licenses are recognised correctly, but there was a problem with merging your projects into each other. I will take a deeper look to that today!

**Comment by reiz** [comment]
@manoelcampos By the way. In order to test the whole thing for your organisation I added myself to your team here: https://www.versioneye.com/organisations/manoelcampos/teams/Owners. Will remove myself as soon everything works like expected.

**Comment by reiz** [comment]
Hi @manoelcampos This is how your project looks like if you don't hard code the project ID into the pom.xml: https://www.versioneye.com/user/projects/586ad564cf4f52001236d935?child=summary#tab-dependencies. Now all the sub modules show up as well. 

I can see that the licenses of the submodules are marked as unknown, that's simply because VersionEye is reading the licenses from public repositories like Maven central and I guess you didn't published your project there yet. Correct?

**Comment by reiz** [comment]
Hi @manoelcampos. What is the reason to use the submodules as a dependency here: https://github.com/manoelcampos/cloudsim-plus/blob/master/pom.xml#L233-L247 ? The parent pom.xml project doesn't have any source code associated to it. All the source code is in the sub modules. So why using them as dependency at this point?

**Comment by manoelcampos** [comment]
Hello @reiz, thanks for your reply.

> The first thing which looks odd to me is that you are hard coding the project ID into the pom.xml

I thought I had the option to let the plugin to create the versioneye.properties or I manually insert the project ID inside my pom.xml, since I didn't want a new file to track. But it is clear now.

> I send you a pull request here which is removing that. 

Thanks, I've just approved it.

> Other from that I saw that the licenses are recognised correctly, but there was a problem with merging your projects into each other. I will take a deeper look to that today!

My project has 4 modules, thus there are 5 pom.xml. When I created the project using mvn, it complained that I reached the subscription limit, once the free plan allows just 4 projects. I don't know if this issue is because I inserted the project ID inside the pom. If it isn't, I'm wondering if wouldn't be possible to count such a kind of multi-module project as a single project.

> In order to test the whole thing for your organisation I added myself to your team here

No problem 😄 

> I can see that the licenses of the submodules are marked as unknown, that's simply because VersionEye is reading the licenses from public repositories like Maven central and I guess you didn't published your project there yet. Correct?

Correct. I supposed that, but I'm just publishing it there where I reach a first stable release. Anyway, I couldn't find such an information.

> What is the reason to use the submodules as a dependency here: https://github.com/manoelcampos/cloudsim-plus/blob/master/pom.xml#L233-L247 ?

Well, that was just legacy code that I didn't even realised it would be a problem. But I just performed a cleanup and everything is building fine. 

Thank you so much for such an awesome tool and for the help 😄

**Comment by reiz** [comment]
Hi @manoelcampos. 

You can put the Project ID into the pom.xml file if you have a simple Maven Project with 1 single pom.xml file. But if you have a maven reactor build you should remove the Project ID from pom.xml and go ahead with the versioneye.properties files. 

Currently you can have 1 private project for free and projects created through the API are considered as private projects. That causes some problems with Maven Reactor builds because they contain multiple projects. I just bumped up the limits for your organisation to solve this problem for you. 

The Maven Plugin resolves your dependencies locally and only sends a pom.json to the VersionEye API. The pom.json format is documented here: https://github.com/versioneye/pom_json_format. As you can see it only contains the names and versions of your dependencies. On the server we check which licenses we have to that names and versions in our database. As your modules are not published to Maven central we don't have information to them in our database. 
Now we could extend the VersionEye Maven Plugin to search for licenses locally and include that information into the pom.json file as well. That would be a new feature.

**Comment by manoelcampos** [comment]
Hi @reiz 
Thanks for the information and for increasing the limit for me.
I really appreciate that 😄

**Comment by manoelcampos** [comment]
Hi @reiz 

Thanks for extending the limits for me and for the information.
I've just sent a [pulll request](https://github.com/versioneye/versioneye_maven_plugin/pull/73) for the feature you mentioned. I hope it may be useful.
